name: Max-parllel example
on: workflow_dispatch


jobs:
  sample:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        version: [1,2,3,4,5]
    steps:
      - run: echo "version = ${{matrix.version}}"    
  
