name: Repo vars & secrets 
on: workflow_dispatch

jobs:
  demo:
   runs-on: ubuntu-latest
   steps:
     - name: show repository variable
       run: echo "Comapny name is ${{vars.COMAPANY}}"

     - name: Use secret key
       env:
         KEY: ${{secrets.API_KEY}}
       run: |
        echo "secret key received"
        echo "$KEY"
         
