name: File operations
on : push

jobs:
    files:
        runs-on: ubuntu-latest

        steps:


            - name: create one file
              run: echo "sunil learn devops" > devops.txt

            - name: display the content of file
              run: cat devops.txt
              
            - name: display the date
              run: date 
              
            - name: display files & directories
              run: ls -lrth
              
            - name: display the present location
              run: pwd   