name: Time-out example
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: start
        run: echo "job started"

      - name: long sleep
        run: sleep 360

      - name: end
        run: echo "job ended"
  
