name: validating without checkout
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

       - name: checkout the repo
         uses: actions/checkout@v7

       - name: Disaply the file content
         run: |
             cat devops.txt
             chmod +x uptime.sh
             ./uptime.sh

      
         

        
