name: without concurrency demo
on: workflow_dispatch

jobs:
  demo:
   runs-on: ubuntu-latest
   steps:
     - run: |
         echo "Running workflow"
         echo "sleep 300"
         echo :finished"
